### ISSUE TITLE
RF Remote is less responsive than before.

### ISSUE THREAD

**Issue by NonaSuomy** [rh1rich/esphome-ifan-remote#1]
Hello,

Tested the new build out and the RF remote is less responsive than using SSIEB's iFan04 RF library. 

Takes multiple clicks of the remote buttons for it to function some times. Very intermitted.

**Comment by rh1rich** [comment]
I suspect that the newly created external component is not very performant. I am currently working on an optimized version, but it will take some time. The removal of the custom components unfortunately took me by surprise.

**Comment by NonaSuomy** [comment]
Also any idea why when clicking buttons they randomly do other things? ( press light, fan starts, etc. and opposite )

**Comment by Linwood-F** [comment]
Just FWIW last night I skimmed the new version to modify mine (long irrelevant story but needed to do that to get some changes I wanted from the original). 

I did not find the remote any different, still seems instant, and all buttons do the expected things.   Now it does seem to require a second (+/-) between pushes or the second push is ignored (easily seen on the buzzer button), but I never do that normally so no idea if that's new and it's certainly not bad (maybe even good as a debounce). 

Thank you for getting an update out that works, was very worried about the new esphome, had to change a lot of my routines in minor ways (platform change) but this one worried me as I had no idea how external components worked.

**Comment by NonaSuomy** [comment]
I have 3 units that all have the same issues and do the same thing. We are HEAVY remote users. Most people say things like it doesn't matter because they never use the remote. Issues like having to tap the buttons multiple times are pretty brutal. I also reuse the beep button and other buttons to turn on/off the bedside lights, and other room lights etc. So these issues are very noticeable.

If you are not a heavy user, you probably would not notice your device selecting the wrong thing, like selecting a different speed than what you pushed or being unresponsive. Having to click the button multiple times is being unresponsive and not a feature.

Your second push is probably ignored because there is a 500ms delay in the default YAML code in all the other buttons.

My iFan04 has the power always on and the wall switch is connected to a GPIO04 on the fan controller to physically turn the light off as well, but it doesn't touch the power. I wonder if most people are using the wall switch to recycle the power to the device and then it responds better.

**Comment by Linwood-F** [comment]
I wonder if it's different variations of the remote or iFan.  I have four of them, and use the remote virtually all the time on the one in my office.  I do not have any connections (other than ac110v) to the iFan though.  I'm not trying to diminish your experience, only provide a data point -- maybe there is some variation.  

I should also note mine strips out all the stuff I do not use (well, other than buzzer), so all the sensors for wifi, reboot, fan boost, etc. are just not there.  It's possible that indirectly in adapting the code I "fixed" something by a slash and burn approach, though I doubt it.

**Comment by NonaSuomy** [comment]
Does your ac110v wall switch power the iFan04 controller and do you ever use it to turn on/off the controller? Most people have it setup this way.
Do you leave the switch on 24/7 and then just use the RF remote 100% of the time or you flip the 110 switch off/on at the wall when you leave the room sometimes etc.

Also are you saying that every time you have pushed the RF remote button it works 100%? Or that it never worked 100% even before switching the code, and it just works the same as it did before ie not working 100% and working intermittent where you have to press the button multiple times for more than just the buzzer button?

As it would be nice if it worked better than it did before as well.

**Comment by Linwood-F** [comment]
No, I wired across the wall switch and replaced it with a Lutron Pico because the wall switch has no neutral (old house).  So the iFan is powered all the time.

I just tried it from the remote.  Pushing about at 2 second intervals I turned the light on and off six times, and turned the fan on low and back off six times, and it didn't miss a single time.

**Comment by NonaSuomy** [comment]
What about if it rests for a while and it's the first time you have pressed it?

You are using the OEM sonoff RF remote or the lutron pico to control the ifan?

**Comment by Linwood-F** [comment]
At least one test just now with the light it worked fine.  And yes, the one that came with it.   The pico is mounted on the wall if I am just walking into the room, but been at my desk this whole time.  Before and after the software upgrade have not noticed it ever missing (well, except when I flip it upside down and push the wrong button, which is frequent).

**Comment by NonaSuomy** [comment]
Does the pico control the ifan through HA commands? Can you post your full yaml?

**Comment by Linwood-F** [comment]
Sure.  Though it has a blueprint so it looks long.  The top and bottom button control the light, the center is fan toggle, the up is faster (and on if needed) and down is slower (and on if needed, only the center turns the fan off): 

    alias: Office Pico as IFAN04 controller
    description: ""
    use_blueprint:
      path: LEF/IFan04_Blueprint.yaml
      input:
        pico_remote: e3d5d9ab4aa4db6f0510a36b716206d1
        target_fan: fan.office_fan
        target_light: light.office_fan

Blueprint: 

```
blueprint:                                                                                                                                                                                                                         
  name: Pico as IFAN04 controller                                                                                                                                                                                                  
  description: "Must be 5 button controller PJ2-3BRL-GXX-X01 and iFAN04"                                                                                                                                                           
  domain: automation                                                                                                                                                                                                               
  input:                                                                                                                                                                                                                           
    pico_remote:                                                                                                                                                                                                                   
      name: Pico Remote                                                                                                                                                                                                            
      description: 'Select the pico remote to configure:'                                                                                                                                                                          
      selector:                                                                                                                                                                                                                    
        device:                                                                                                                                                                                                                    
          model: PJ2-3BRL-GXX-X01 (Pico3ButtonRaiseLower)                                                                                                                                                                          
          multiple: false                                                                                                                                                                                                          
    target_fan:                                                                                                                                                                                                                    
      name: Which fan is affected                                                                                                                                                                                                  
      description: determine the fan                                                                                                                                                                                               
      selector:                                                                                                                                                                                                                    
        entity:                                                                                                                                                                                                                    
          domain: fan                                                                                                                                                                                                              
          multiple: false                                                                                                                                                                                                          
    target_light:                                                                                                                                                                                                                  
      name: Which light entity attached to (same) fan                                                                                                                                                                              
      description: determine the light                                                                                                                                                                                             
      selector:                                                                                                                                                                                                                    
        entity:                                                                                                                                                                                                                    
          domain: light                                                                                                                                                                                                            
          multiple: false                                                                                                                                                                                                          
                                                                                                                                                                                                                                   
variables:
  tf: !input target_fan
   
trigger:
- platform: device
  device_id: !input pico_remote
  domain: lutron_caseta
  type: press
  subtype: 'on'
- platform: device
  device_id: !input pico_remote
  domain: lutron_caseta
  type: press
  subtype: raise
- platform: device
  device_id: !input pico_remote
  domain: lutron_caseta
  type: press
  subtype: stop
- platform: device
  device_id: !input pico_remote
  domain: lutron_caseta
  type: press
  subtype: lower
- platform: device
  device_id: !input pico_remote
  domain: lutron_caseta
  type: press
  subtype: 'off'
condition: []

action:
- choose:
  - conditions: '{{ trigger.event.data.action == "press" }}'
    sequence:
    - choose:
      # top
      - conditions: '{{ trigger.event.data.button_number == 2 }}'
        sequence: 
        - service: light.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: !input target_light
      # up    
      - conditions: '{{ trigger.event.data.button_number == 5 }}'
        sequence: 
        - service: fan.increase_speed
          metadata: {}
          data: {}
          target:
            entity_id: !input target_fan

      # stop (middle, round button)         
      - conditions: '{{ (trigger.event.data.button_number == 3) }}'
        sequence: 
        - choose: 
          - conditions: 
            - condition: state
              entity_id: !input target_fan
              state: 'off' 
            sequence: 
            - service: fan.turn_on 
              entity_id: !input target_fan
          - conditions: 
            - condition: state
              entity_id: !input target_fan
              state: 'on' 
            sequence: 
            - service: fan.turn_off 
              entity_id: !input target_fan
          default: []  
          
          
      # lower
      - conditions: '{{ trigger.event.data.button_number == 6 }}'
        sequence: 
        - service: fan.decrease_speed
          metadata: {}
          data: {}
          target:
            entity_id: !input target_fan

      # off
      - conditions: '{{ trigger.event.data.button_number == 4 }}'
        sequence: 
        - service: light.turn_off
          metadata: {}
          data: {}
          target:
            entity_id:  !input target_light
  default: []
mode: single
max: 2

```

**Comment by NonaSuomy** [comment]
Can you post your iFan04 esphome full yaml as well?

**Comment by Linwood-F** [comment]
Yeah, it's a mess.  Here's the wrapper: 

```
substitutions:
  devicename: "office-fan"
  friendly_devicename: Office Fan
  fan_startup_boost_time: 5s
  ipaddr: 192.168.130.215

packages:
  ifan: !include templates/ifan04-template.yaml

```

Here's the first template: 

```
esphome:
  name: $devicename
  friendly_name: $friendly_devicename
  includes:
    - ifan_remote.h
  on_boot:
    priority: 600
    then:
    - switch.turn_off: buzzer_enabled
    - output.turn_off: buzzer

external_components:
  - source:
      type: git
      url: https://github.com/rh1rich/esphome-ifan-remote
  - source:
      type: git
      url: https://github.com/rh1rich/esphome-morse-code

packages:
  stuff: !include standard-setup-template.yaml
  more:  !include ha-time-template.yaml

# https://github.com/rh1rich/esphome-ifan04

esp8266:
  board: esp8285
  framework:
    version: latest
  early_pin_init: true
  restore_from_flash: true

preferences:
  flash_write_interval: 5min

# Enable logging
# But disable it via UART0, because UART0 is used by the RF receiver
logger:
  baud_rate: 0
#  level: VERBOSE


# GPIO00 ... Button
# GPIO01 ... UART0 TX
# GPIO03 ... UART0 RX (RF-Remote)
# GPIO04 ... I2C SDA (TP11 D_RX on PCB backside)
# GPIO05 ... I2C SCL (TP10 D_TX on PCB backside)
# GPIO09 ... Light Relay (D)
# GPIO10 ... Buzzer
# GPIO12 ... Fan Relay 2 (D11, 3uF cap on IFAN04-H)
# GPIO13 ... LED
# GPIO14 ... Fan Relay 1 (D5, 2.5uF cap on IFAN04-H)
# GPIO15 ... Fan Relay 3 (D13, no cap)

status_led:
  pin:
    number: GPIO13
    inverted: true

# UART0 (GPIO03) is used by the RF-receiver to send the received RF-commands
# to the ESP.
uart:
  rx_pin: GPIO03
  baud_rate: 9600
  id: uart_bus

# I2C via the test points TP10 (= GPIO05) and TP11 (= GPIO04) on the PCB.
i2c:
  sda: GPIO04
  scl: GPIO05
  frequency: 200kHz

output:
  - platform: gpio
    id: light_relay
    pin:
      number: GPIO09
      inverted: true
  - platform: gpio
    id: buzzer
    pin:
      number: GPIO10
      inverted: true
  - platform: gpio
    id: fan_relay_1
    pin: GPIO14
  - platform: gpio
    id: fan_relay_2
    pin: GPIO12
  - platform: gpio
    id: fan_relay_3
    pin: GPIO15
  - platform: template
    id: fan_relays
    type: float
    write_action:
      - if:
          condition:
            lambda: return (state < 0.3);
          then:
            - script.execute:
                id: buzzer_play
                action: fan_off
            - script.execute:
                id: fan_speed_set
                speed: 0
      - if:
          condition:
            lambda: return ((state >= 0.3) && (state < 0.6));
          then:
            - script.execute:
                id: buzzer_play
                action: fan_1
            - script.execute:
                id: fan_speed_set
                speed: 1
      - if:
          condition:
            lambda: return ((state >= 0.6) && (state < 0.9));
          then:
            - script.execute:
                id: buzzer_play
                action: fan_2
            - script.execute:
                id: fan_speed_set
                speed: 2
      - if:
          condition:
            lambda: return (state >= 0.9);
          then:
            - script.execute:
                id: buzzer_play
                action: fan_3
            - script.execute:
                id: fan_speed_set
                speed: 3

morse_code:
  output: buzzer
  dit_duration: 50

light:
  - platform: binary
    name: ' '
    id: light_comp
    output: light_relay

fan:
  - platform: speed
    name: ' '
    id: fan_comp
    output: fan_relays
    speed_count: 3

switch:
  - platform: template
    name: 'Buzzer enabled'
    id: buzzer_enabled
    entity_category: config
    optimistic: True
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - script.execute:
          id: buzzer_play
          action: buzzer_on
    on_turn_off:
      - script.execute:
          id: buzzer_play
          action: buzzer_off

binary_sensor:
  - platform: gpio
    name: "Button"
    pin:
      number: GPIO00
      inverted: true

# Remote commands via UART0
#  RX: GPIO03
#
# The numbering of the following remote control buttons
# starts with the top left button (1) and ends with the
# bottom right button (8).
#
# 1 (Light)           = (AA55) 0104 000104 (0A)
# 2 (Mute)            = (AA55) 0106 000101 (09)
# 3 (Fan high)        = (AA55) 0104 000103 (09)
# 4 (Fan mid)         = (AA55) 0104 000102 (08)
# 5 (Fan off)         = (AA55) 0104 000100 (06)
# 6 (Fan low)         = (AA55) 0104 000101 (07)
# 7 (RF Clearing)     = (AA55) 0101 000102 (05)
# 7 (RF Clearing 5s)  = (AA55) 0107 000101 (0A) clears the connection between remote control and receiver!!
# 8 (WiFi Pairing)    = (AA55) 0101 000102 (05)
# 8 (WiFi Pairing 5s) = (AA55) 0101 000101 (04)

ifan_remote:
  on_command:
    then:
      - logger.log:
          format: "RC command '%04X:%06X' received."
          args: [ 'command.high','command.low' ]
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000100);
          then:
            - fan.turn_off: fan_comp
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000101);
          then:
            - fan.turn_on:
                id: fan_comp
                speed: 1
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000102);
          then:
            - fan.turn_on:
                id: fan_comp
                speed: 2
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000103);
          then:
            - fan.turn_on:
                id: fan_comp
                speed: 3
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000104);
          then:
          - light.toggle: light_comp

      - if:
          condition:
            lambda: return (command.high == 0x0106 && command.low == 0x000101);
          then:
            - switch.toggle: buzzer_enabled
      - if:
          condition:
            lambda: return (command.high == 0x0101 && command.low == 0x000102);
          then:
            - script.execute:
                id: buzzer_play
                action: short
      - if:
          condition:
            lambda: return (command.high == 0x0101 && command.low == 0x000101);
          then:
            - script.execute:
                id: buzzer_play
                action: long
      - if:
          condition:
            lambda: return (command.high == 0x0107 && command.low == 0x000101);
          then:
            - script.execute:
                id: buzzer_play
                action: long

globals:
  - id: last_fan_speed
    type: int
    restore_value: no
    initial_value: "0"

script:
  - id: fan_speed_set
    mode: restart
    parameters:
      speed: int
    then:
      - if:
          condition:
            lambda: return (speed == 0);
          then:
            - output.turn_off: fan_relay_1
            - output.turn_off: fan_relay_2
            - output.turn_off: fan_relay_3
      - if:
          condition:
            lambda: return (speed > 0);
          then:
            - if:
                condition:
                  lambda: return (speed == 1);
                then:    # enable cap 1
                  - output.turn_on: fan_relay_1
                  - output.turn_off: fan_relay_2
                  - output.turn_off: fan_relay_3
            - if:
                condition:
                  lambda: return (speed == 2);
                then:    # enable cap 1 & 2
                  - output.turn_on: fan_relay_1
                  - output.turn_on: fan_relay_2
                  - output.turn_off: fan_relay_3
            - if:
                condition:
                  lambda: return (speed == 3);
                then:    # no caps
                  - output.turn_off: fan_relay_1
                  - output.turn_off: fan_relay_2
                  - output.turn_on: fan_relay_3
      - lambda: |-
          id(last_fan_speed) = speed;
  - id: buzzer_play
    mode: restart
    parameters:
      action: string
    then:
      - if:
          condition:
            lambda: return (action == "buzzer_off");
          then:
            - morse_code.start:
                text: "E"    # .
      - if:
          condition:
            lambda: return (action == "buzzer_on");
          then:
            - morse_code.start:
                text: "I"    # ..
      - if:
          condition:
            lambda: return id(buzzer_enabled).state && (action == "fan_off");
          then:
            - morse_code.start:
                text: "T"    # -
      - if:
          condition:
            lambda: return id(buzzer_enabled).state && (action == "fan_1");
          then:
            - morse_code.start:
                text: "N"    # -.
      - if:
          condition:
            lambda: return id(buzzer_enabled).state && (action == "fan_2");
          then:
            - morse_code.start:
                text: "D"    # -..
      - if:
          condition:
            lambda: return id(buzzer_enabled).state && (action == "fan_3");
          then:
            - morse_code.start:
                text: "B"    # -...
      - if:
          condition:
            lambda: return id(buzzer_enabled).state && (action == "short");
          then:
            - morse_code.start:
                text: "E"    # .
      - if:
          condition:
            lambda: return id(buzzer_enabled).state && (action == "long");
          then:
            - morse_code.start:
                text: "T"    # -

```

And those two included templates: 


```
time:
  - platform: homeassistant
    id: LEF_hasTime
    timezone: America/New_York
    on_time_sync: 
      then:
        - logger.log: "Syncronized system clock"
        - lambda: |-
            static int reportedBoot = 0;
            if(!reportedBoot) {
                reportedBoot = 1;
                char str[20];
                time_t currTime = id(LEF_hasTime).now().timestamp;
                strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
                id(LEF_Reboot).publish_state(str);
            }

text_sensor:
  - platform: template
    update_interval: never
    name: Rebooted
    id: LEF_Reboot
    internal: true 

```
```

logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: !secret ota_password

#captive_portal:

web_server:
  port: 80
  include_internal: true

wifi:
  reboot_timeout: 10min
  power_save_mode: none
  domain: !secret domain
  manual_ip:
    static_ip: ${ipaddr}
    gateway: 192.168.130.1
    subnet: 255.255.255.0
    dns1: 192.168.130.1
    
  networks: 
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret ap_password

debug:
  update_interval: 30s
  
sensor:
  # Reports the WiFi signal strength
  # Also will reboot if signal is too low after it checks a while (see loop counts below)
  - platform: wifi_signal
    name: Signal
    id: wifisignalid
    update_interval: 120s
    accuracy_decimals: 0
    filters:
      - sliding_window_moving_average: 
          window_size: 6
          send_every: 6
    on_value:
      then: 
        - lambda: |-
            static int loops=0; 
            static int maxLoop = 15;
            float rawdb = id(wifisignalid).raw_state; 
            if(rawdb < -88) {
              if(++loops > maxLoop) {
                ESP_LOGI("main", "Raw Value signal will cause reboot: %f", id(wifisignalid).raw_state);
                id(restartid).turn_on(); 
              } else {
                ESP_LOGI("main", "Raw Value signal would cause reboot but only on loop %d of %d: %f", loops, maxLoop, id(wifisignalid).raw_state);
              }
            } else {
              ESP_LOGI("main", "Raw Value signal will not cause reboot: %f", id(wifisignalid).raw_state);
              loops=0;
            }

text_sensor: 
  - platform: wifi_info
    bssid:
      update_interval: 60s
      name: BSSID
      internal: true 
  ### includes reset reason in string
  - platform: debug
    device:
      name: "Device Info"
      internal: true 

switch:
  - platform: restart
    id: restartid
    name: reboot
    restore_mode: restore_default_off

```
